%YAML 1.1
--- 
name: Local Assistant
version: 1.0.0
schema: v1
models:

  - name: Autodetect
    provider: ollama
    apiBase: ${{ secrets.OPENAI_BASE_URL }}
    apikey: ${{ secrets.OPENAI_API_KEY }}
    model: AUTODETECT
    roles:
      - chat
      - edit
      - apply
      - rerank
      - autocomplete